name: RuboCop

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install RuboCop
        run: gem install rubocop

      - name: Run RuboCop
        run: rubocop

      - name: Fail if any offenses are found
        if: ${{ steps.rubocop.outputs.exit-code != 0 }}
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              body: 'RuboCop found offenses. Please fix them before merging.'
            })