name: RuboCop

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install RuboCop
        run: sudo gem install rubocop -v 0.57.2

      - name: Run RuboCop
        run: rubocop