name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.1.2'
      - name: Run tests
        run: ruby /tests/all.rb